# Generated by Django 5.2.17 on 2026-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_auto_leave_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableleave',
            name='auto_period_basis',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='historicalavailableleave',
            name='auto_period_basis',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
    ]
