# Generated by Django 5.2.18 on 2026-10-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_availableleave_auto_period_basis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-id'], 'permissions': (('can_view_on_leave', 'Can View On Leave'), ('override_service_gate', 'Can record paid leave within the first three months of service')), 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
    ]
