# Generated by Django 5.2.17 on 2026-09-21 07:12

import django.db.models.deletion
import employee.singapore_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Preferred Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.CreateModel(
            name='SingaporeDetailsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=20)),
                ('fields', models.JSONField(default=list)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employee.employee')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SingaporeEmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(blank=True, choices=[('NRIC', 'NRIC'), ('FIN', 'FIN')], max_length=4)),
                ('identity_number', employee.singapore_fields.EncryptedHRTextField(blank=True, default='', max_length=9)),
                ('residency_status', models.CharField(blank=True, choices=[('citizen', 'Singapore Citizen'), ('pr', 'Permanent Resident'), ('foreigner', 'Foreigner')], max_length=12)),
                ('pr_effective_date', models.DateField(blank=True, null=True)),
                ('work_pass_type', models.CharField(blank=True, choices=[('EP', 'Employment Pass'), ('S_PASS', 'S Pass'), ('WORK_PERMIT', 'Work Permit'), ('PEP', 'Personalised Employment Pass'), ('ENTREPASS', 'EntrePass'), ('ONE_PASS', 'ONE Pass'), ('LTVP', 'Long-Term Visit Pass'), ('DP', "Dependant's Pass"), ('OTHER', 'Other')], max_length=30)),
                ('work_pass_number', employee.singapore_fields.EncryptedHRTextField(blank=True, default='', max_length=50)),
                ('work_pass_expiry', models.DateField(blank=True, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Singapore employment details',
                'verbose_name_plural': 'Singapore employment details',
                'default_permissions': ('view', 'change'),
            },
        ),
    ]
