# Generated by Django 5.2.18 on 2026-10-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_singapore_employment_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingaporeContributionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(verbose_name='Effective salary month')),
                ('primary_race', models.CharField(choices=[('chinese', 'Chinese'), ('malay', 'Malay'), ('indian', 'Indian'), ('eurasian', 'Eurasian'), ('other', 'Other')], max_length=12, verbose_name='Primary race on NRIC / employee declaration')),
                ('muslim_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Muslim')),
                ('residency_status', models.CharField(choices=[('citizen', 'Singapore Citizen'), ('pr', 'Permanent Resident'), ('foreigner', 'Foreigner')], max_length=12, verbose_name='Residency during this period')),
                ('pr_effective_date', models.DateField(blank=True, null=True)),
                ('work_pass_type', models.CharField(blank=True, choices=[('EP', 'Employment Pass'), ('S_PASS', 'S Pass'), ('WORK_PERMIT', 'Work Permit'), ('PEP', 'Personalised Employment Pass'), ('ENTREPASS', 'EntrePass'), ('ONE_PASS', 'ONE Pass'), ('LTVP', 'Long-Term Visit Pass'), ('DP', "Dependant's Pass"), ('OTHER', 'Other')], max_length=30)),
                ('declaration_reference', models.CharField(max_length=255, verbose_name='HR verification / declaration reference')),
                ('student_cpf_exempt', models.BooleanField(default=False, verbose_name='Verified student exemption for CPF / CDAC / ECF / SINDA')),
                ('student_mbmf_exempt', models.BooleanField(default=False, verbose_name='Verified student exemption for MBMF')),
                ('student_exempt_from', models.DateField(blank=True, null=True)),
                ('student_exempt_until', models.DateField(blank=True, null=True)),
                ('student_exemption_reference', models.CharField(blank=True, max_length=255)),
                ('fund_adjustments', models.JSONField(blank=True, default=dict, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employee.employee')),
            ],
            options={
                'ordering': ['-effective_month', '-pk'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['employee', 'effective_month'], name='sg_shg_employee_month')],
            },
        ),
    ]
