# Generated by Django 5.2.17 on 2026-10-01 07:28

from django.db import migrations, models


def classify_statutory_deductions(apps, schema_editor):
    Deduction = apps.get_model("payroll", "Deduction")
    for component in Deduction.objects.using(schema_editor.connection.alias).all():
        label = component.title.strip().upper()
        for code in ("CPF", "CDAC", "ECF", "SINDA", "MBMF"):
            if label == code or label.startswith(code + " "):
                component.statutory_type = code.lower()
                component.save(update_fields=["statutory_type"])
                break


def ensure_history_payment_date(apps, schema_editor):
    model = apps.get_model("payroll", "HistoricalPayslip")
    with schema_editor.connection.cursor() as cursor:
        columns = schema_editor.connection.introspection.get_table_description(cursor, model._meta.db_table)
    existing = next((column for column in columns if column.name == "payment_date"), None)
    if existing:
        if schema_editor.connection.introspection.get_field_type(existing.type_code, existing) != "DateField":
            raise RuntimeError("Existing historical payment_date must be a date column")
        return
    field = models.DateField(blank=True, null=True)
    field.set_attributes_from_name("payment_date")
    schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payslip_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cpf_exempt',
            field=models.BooleanField(default=False, verbose_name='CPF Exempt'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpf_exemption_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CPF Exemption Basis'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payroll_workweek',
            field=models.CharField(blank=True, choices=[('', 'Use shift / company weekly off days'), ('five_day', 'Monday–Friday'), ('six_day', 'Monday–Saturday'), ('seven_day', 'Every day')], default='', help_text='Used for incomplete-month salary. For half-day schedules, select a shift instead.', max_length=16, verbose_name='Payroll Workweek'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sdl_exempt',
            field=models.BooleanField(default=False, verbose_name='SDL Exempt'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sdl_exemption_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SDL Exemption Basis'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='statutory_type',
            field=models.CharField(choices=[('none', 'Other deduction'), ('cpf', 'CPF'), ('cdac', 'CDAC'), ('ecf', 'ECF'), ('sinda', 'SINDA'), ('mbmf', 'MBMF')], default='none', help_text='CPF-exempt internships also exclude CDAC, ECF and SINDA. MBMF follows separate eligibility rules.', max_length=8, verbose_name='Statutory Deduction Type'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='cpf_exempt',
            field=models.BooleanField(default=False, verbose_name='CPF Exempt'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='cpf_exemption_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CPF Exemption Basis'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='payroll_workweek',
            field=models.CharField(blank=True, choices=[('', 'Use shift / company weekly off days'), ('five_day', 'Monday–Friday'), ('six_day', 'Monday–Saturday'), ('seven_day', 'Every day')], default='', help_text='Used for incomplete-month salary. For half-day schedules, select a shift instead.', max_length=16, verbose_name='Payroll Workweek'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='sdl_exempt',
            field=models.BooleanField(default=False, verbose_name='SDL Exempt'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='sdl_exemption_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SDL Exemption Basis'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(ensure_history_payment_date, migrations.RunPython.noop)],
            state_operations=[
                migrations.AddField(
                    model_name='historicalpayslip',
                    name='payment_date',
                    field=models.DateField(blank=True, help_text='Actual salary payment date; defaults to the 6th of the following month, moved to Monday when it falls on a weekend.', null=True, verbose_name='Payment Date'),
                ),
            ],
        ),
        migrations.RunPython(classify_statutory_deductions, migrations.RunPython.noop),
    ]
