# Generated by Django 5.2.18 on 2026-10-08 14:37

import payroll.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_contract_cpf_exempt_contract_cpf_exemption_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='cpf_wage_type',
            field=models.CharField(choices=[('ow', 'CPF Ordinary Wages'), ('aw', 'CPF Additional Wages'), ('excluded', 'Expense Reimbursement / Not CPF Wages')], default='ow', help_text='Taxability is separate. Fixed transport / meal allowances are CPF wages; genuine expense reimbursements are excluded.', max_length=10, verbose_name='CPF Wage Classification'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='prorate_fixed',
            field=models.BooleanField(default=True, help_text='Use payable salary proportion for joining, leaving and unpaid time. One-off items and reimbursements are excluded.', verbose_name='Prorate Fixed Monthly Allowance'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpf_annual_ow_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for Additional Wages before year end. Include OW from all contracts with this employer; review whenever wages change.', max_digits=12, null=True, validators=[payroll.models.models.min_zero], verbose_name='Estimated Annual OW Subject to CPF'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpf_estimate_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CPF Estimate Year'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpf_pr_approval',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CPF Board Approval Reference'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpf_pr_scheme',
            field=models.CharField(choices=[('graduated', 'Graduated employer / employee'), ('full_employer', 'Full employer / graduated employee'), ('full_both', 'Full employer / employee')], default='graduated', max_length=20, verbose_name='PR CPF Scheme'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='cpf_annual_ow_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for Additional Wages before year end. Include OW from all contracts with this employer; review whenever wages change.', max_digits=12, null=True, validators=[payroll.models.models.min_zero], verbose_name='Estimated Annual OW Subject to CPF'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='cpf_estimate_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CPF Estimate Year'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='cpf_pr_approval',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CPF Board Approval Reference'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='cpf_pr_scheme',
            field=models.CharField(choices=[('graduated', 'Graduated employer / employee'), ('full_employer', 'Full employer / graduated employee'), ('full_both', 'Full employer / employee')], default='graduated', max_length=20, verbose_name='PR CPF Scheme'),
        ),
        migrations.AlterField(
            model_name='historicalpayslip',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Defaults to the scheduled 6th of the following month. Confirm the actual payment date after transferring salary.', null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Defaults to the scheduled 6th of the following month. Confirm the actual payment date after transferring salary.', null=True, verbose_name='Payment Date'),
        ),
    ]
