# Generated by Django 5.2.18 on 2026-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_allowance_cpf_wage_type_allowance_prorate_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cpf_pr_scheme_start',
            field=models.DateField(blank=True, help_text='Enter the first day of the effective month stated in CPF Board approval.', null=True, verbose_name='Higher PR CPF Rates Effective Month'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='cpf_pr_scheme_start',
            field=models.DateField(blank=True, help_text='Enter the first day of the effective month stated in CPF Board approval.', null=True, verbose_name='Higher PR CPF Rates Effective Month'),
        ),
    ]
