# Generated by Django 5.2.18 on 2026-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_contract_cpf_pr_scheme_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='shg_excluded_funds',
            field=models.JSONField(blank=True, default=list, help_text="Exclude this allowance only where the fund's rules require it. Ordinary cash allowances remain wages; genuine expense reimbursements use the wage classification above.", verbose_name='SHG wage exclusions'),
        ),
    ]
