# Generated by Django 5.2.18 on 2026-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceconflictresolution_attendancedailyhours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecords',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
